### ISSUE TITLE
Problemas al configurar

### ISSUE THREAD

**Issue by radaramo** [mradzinski/Caster#1]
Tengo problemas al agregar repositorio en gradle cast.

**Comment by mradzinski** [comment]
Hi, if I understood correctly you have issues to add the repository on "grade cast"? 

This is an Android library, there's no such thing as what you had mention, so I'll assume you have issues trying to add the dependency to one of your projects. Please try to be more specific, any specific error? How are you integrating the dependency?

**Comment by radaramo** [comment]
I was trying with the example that is in the library.
My question is if in the example I have to configure something else to make it work?
Because when adding this:

dependencies {
    implementation 'com.github.mradzinski: Caster: 1.2.2'
}

I get an error when executing the example.

**Comment by mradzinski** [comment]
Dependencies are needed if you wanna integrate the library into one of your projects. If you clone the repository and try running the example you shouldn't need to add any dependencies since they are already added

The only thing you need to configure when running the example is the `VIMEO_URL` constant value. You need to change it to whatever M3U URL you have. If you wanna use an MP4 video instead of a M3U then (as stated in the README) you should change `setContentType` from `application/x-mpegURL` to `videos/mp4`.

**Comment by radaramo** [comment]
If I run normally, it only shows the disabled icons. Now add the link m3u8. But it still shows the play, resume, and cast icons disabled.
What is the cause of that?
![image](https://user-images.githubusercontent.com/23094054/43671453-0ee8e0b4-9760-11e8-9875-97db00851e15.png)

**Comment by radaramo** [comment]
It is connected to the same network.
If you have google play services installed.
It is a real device (Huawei P9). It's weird that it can not work.
